### ISSUE TITLE
MacOs version

### ISSUE THREAD

**Issue by timkovik** [Heroes-Profile/HeroesProfile.Uploader#16]

**Comment by Zemill** [comment]
We have

https://github.com/Heroes-Profile/heroesprofile-electron-uploader

Can you try that.  It doesnt have all the same functionality, but should work as a general use uploader

**Comment by timkovik** [comment]
Oh, thx! I'll try it. But I I didn't use the version for windows, so I didn't I have some expectations, except for the upload itself.
