### ISSUE TITLE
Uploads incomplete post-2021/03/11

### ISSUE THREAD

**Issue by JinstonC** [Heroes-Profile/HeroesProfile.Uploader#17]
Since 2021/03/11 my replay uploads are showing as incomplete even though they are complete replays.

![image](https://user-images.githubusercontent.com/50266824/110901374-97585f80-8347-11eb-808b-e0bb33f5a5f3.png)

**Comment by Venando** [comment]
I had the same issue one time when hotslog Uploader and HeroesProfile.Uploader started to upload replays simultaneously.
I "resolved" issue by manually starting HeroesProfile.Uploader after hotslog uploder finished loading.

**Comment by Zemill** [comment]
@JinstonC Can you attach one of those replays to this issue

**Comment by JinstonC** [comment]
The issue seems to be resolved. I deleted the XML files to reupload and they worked fine. Here is a replay just in case. 
[2021-03-11 22.09.46 Towers of Doom.StormReplay.zip](https://github.com/Heroes-Profile/HeroesProfile.Uploader/files/6162317/2021-03-11.22.09.46.Towers.of.Doom.StormReplay.zip)
