### ISSUE TITLE
Duplicate match is not removed

### ISSUE THREAD

**Issue by tastypurgen** [Heroes-Profile/HeroesProfile.Uploader#21]
![image](https://user-images.githubusercontent.com/43437265/120094506-770b9600-c129-11eb-8f47-7446c23a6e9c.png)
![image](https://user-images.githubusercontent.com/43437265/120094535-95719180-c129-11eb-9082-fa2f415ca7fd.png)

If a match is duplicated then it is not removed from replays folder

**Comment by Zemill** [comment]
Replay deletion has been removed from the uploader
