### ISSUE TITLE
HeroesProfile.Uploder doesn't open properly 

### ISSUE THREAD

**Issue by leonardoD4C** [Heroes-Profile/HeroesProfile.Uploader#25]
I tried to open programm, all i get is an icon on the task bar and empty black window, nothing else.

I've already deleted and downloaded it one more time, tried to open and close it through programm manager; nothing helpes
![1](https://user-images.githubusercontent.com/95985316/145692971-a83f709f-8b8a-4d6f-8aa3-9470e5e29b77.jpg)
![2](https://user-images.githubusercontent.com/95985316/145692972-a029f150-d14b-48e9-906a-dc191c7d1d4c.jpg)

**Comment by Zemill** [comment]
I've not seen this issue before.  Are you on windows 10/11.   Any other errors showing up?   Did you check the website to see if the games were uploaded regardless?

**Comment by leonardoD4C** [comment]
I have 10 windows. No other errors, and games are uploaded regardless this issue, but I can use programm properly

**Comment by Zemill** [comment]
I am still looking into this.  Are your graphics drivers updated?

Is there any functionality you are trying to use beyond uploading?
