### ISSUE TITLE
Config File Corruption

### ISSUE THREAD

**Issue by triclops200** [Heroes-Profile/HeroesProfile.Uploader#28]
When starting the application, I get the following error.
![image](https://user-images.githubusercontent.com/343522/162287157-0a716a86-dd18-46cd-a770-d06605842b32.png)
The contents of user.config is just 2K of null bytes. If I delete this file, it comes back as 2k of null bytes.

**Comment by Zemill** [comment]
What version of windows are you using?  Attached below is a working config from my computer, let me know if that works for you

[config.zip](https://github.com/Heroes-Profile/HeroesProfile.Uploader/files/8451947/config.zip)

**Comment by triclops200** [comment]
either 2.1.1 fixed it, or using that config did, but it works now and recreates the config correctly when it is deleted

Thanks!

**Comment by Zemill** [comment]
I removed some unused settings that were populating in the config, so maybe that was the issue.  I'll close this

**Comment by Rice-SD** [comment]
Been having the same issue for months (I have it set to start at startup so I've mostly been ignoring it), latest version here on Github- 2.4.0.0 I believe. Using your config fixed it, thanks @Zemill!

**Comment by Irazall** [comment]
Thanks :) helped!

**Comment by Irazall** [comment]
Could someone create an updated version with a fix, please?

**Comment by Zemill** [comment]
If I find time I will take a look...easiest method I think without looking would be to change the config name to something else, that way I dont have to try and delete it on users computers etc....
