### ISSUE TITLE
"Please update your uploaders. An API site architecture change has occured that requires it. Thanks"

### ISSUE THREAD

**Issue by VirtueAvatar** [Heroes-Profile/HeroesProfile.Uploader#36]
This message "Please update your uploaders. An API site architecture change has occured that requires it. Thanks" is on HeroesProfile, I don't know how long that's been there but there doesn't look like there's been an update for months?

I didn't update mine and I'm on 2.4.1.

**Comment by Zemill** [comment]
This message was mainly meant for anyone who had failed to update their uploaders in the 3-4 months between this 2.4.1 update and the API site change that occurred this month

You are fine at 2.4.1
