### ISSUE TITLE
Auto-Updates using Squirrel not working

### ISSUE THREAD

**Issue by Zemill** [Heroes-Profile/HeroesProfile.Uploader#4]
I do not think the auto updating functionality is working

https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/getting-started/5-updating.md

**Comment by Zemill** [comment]
Seems the request to check the repo for a new release fails

`WARN: Error checking for updates System.Net.WebException: The request was aborted: The connection was closed unexpectedly.`

https://github.com/Heroes-Profile/HeroesProfile.Uploader/blob/27185096ace0b00aff0b6d6eb17587541dfcb46d/Heroesprofile.Uploader.Windows/App.xaml.cs#L200

**Comment by koliva8245** [comment]
In your releases you need to upload the `RELEASES`, `<file>-x.x.x-delta.nupkg`, and  `<file>-x.x.x-full.nupkg` files.

How it works is that the `RELEASES` file is read to determine if any updates are available and which to download.

**Comment by Zemill** [comment]
Alright, so I have released v1.0.2 that contains the missing data.  @koliva8245 Will the release of v1.0.0 update to v1.0.2 even though I didnt include those files on that release?

**Comment by koliva8245** [comment]
For v1.0.0 you'll need to include the `RELEASES` file and the full nupkg file.

**Comment by Zemill** [comment]
Alright, so I got it working to know that a change occured, and to try and pull that change.  But apparently Squirrel doesn't work with the latest release of SharpCompress, and the ReplayParser package uses the latest release.  

https://github.com/Squirrel/Squirrel.Windows/issues/1253

Apparently the release that works is release 0.18.0, and the replay parser is on 0.24.0.

I do not have any experience with this type of mismatch and I am not sure how to resolve it.  Thoughts?  Simply downgrading causes the parser to crash

**Comment by koliva8245** [comment]
Well you can either fork the Replay Parser, replace SharpCompress with a compatible version or better yet barret's replay parser could be updated to use dotnetzip instead.

**Comment by Zemill** [comment]
Ok, I was afraid that was going to be the answer.  Barret's parser already has the code defined to use dotnetzip, so it was just a matter of switching the constant.  Wonder why he isn't using it though.
