### ISSUE TITLE
Incorrect League (Bronze 4 instead of Bronze 2) in Storm League

### ISSUE THREAD

**Issue by nightblade9** [Heroes-Profile/HeroesProfile.Uploader#41]
I completed four matches: three placement matches and one actual match. According to [my profile page on Heroes Profile](https://www.heroesprofile.com/Player/nightblade9/10074525/1/MMR), I'm in `Bronze 4`. According to Heroes of the Storm, I'm in `Bronze 2`.

![image](https://github.com/user-attachments/assets/83f59408-237b-4e34-8264-9eb177e6eaf1)

**Comment by Zemill** [comment]
MMR is not exposed in the replay files, and neither is rank. 


The MMR and rank you see on our website is our own and does not map to your in game rank.   While we do attempt to have it be as close as possible, it is unlikely to be perfect.

**Comment by nightblade9** [comment]
Is this info stated anywhere on the website or in the source repo? This is the first I've heard that they are two different numbers.

**Comment by Zemill** [comment]
> Is this info stated anywhere on the website or in the source repo? This is the first I've heard that they are two different numbers.

Thats a good question.  I do not think it is anymore.  We rewrote the site about a year ago now and the FAQ page didn't make the cut.  That information was standard Hots knowledge back when the site was written, but as new player come in I think that knowledge isn't so obvious anymore.

If you want to open an enhancement request to get that added, this type of query/request is better suited for the Heroesprofile repository, specifically https://github.com/Heroes-Profile/heroesprofile/discussions/new?category=ideas

On the Heroesprofile website if you check out the Help menu you can see there are two links for doing an issue report or enhancement request

Let me know if you have any other questions

**Comment by nightblade9** [comment]
OK. Well, if you ever decide you want to try to make them match, and you need data, you can always ping me on GitHub.

**Comment by Zemill** [comment]
> OK. Well, if you ever decide you want to try to make them match, and you need data, you can always ping me on GitHub.

Do you have any recommendations for how to achieve this?

**Comment by nightblade9** [comment]
> Do you have any recommendations for how to achieve this?

No, I don't know how MMR works. You're the expert here. I'm just offering to provide data from my stats if that helps.

**Comment by Zemill** [comment]
> > Do you have any recommendations for how to achieve this?
> 
> 
> 
> No, I don't know how MMR works. You're the expert here. I'm just offering to provide data from my stats if that helps.
> 
> 

I see.   Unfortunately there are two main issues with trying to map our MMR system to blizzards rank.  1:  they don't expose MMR or tell us what system they use to calculate MMR or if it's scaled.  2: we don't have access to 100% of the games played.  So it's impossible to get a 100% accurate MMR value.  

We use a standard MMR calculating approach paired with blizzards own released rank distribution percents to get our ranks, and I am not sure there is a better way to do it without adding in image capture AI tech to the uploader to grab ranks from your screen/game/ui when you actively play the game.
