### ISSUE TITLE
Uploader incorrectly flagging games as duplicate

### ISSUE THREAD

**Issue by nightblade9** [Heroes-Profile/HeroesProfile.Uploader#43]
Thought I saw this a couple of times, but wasn't sure. Now, I am.

I just finished a pair of games. The first is Xul, win; the second is Xul, loss.  The uploader indicates the first game is a duplicate, and marks the second as uploaded.

![image](https://github.com/user-attachments/assets/f5c94501-a69a-43b0-97bf-6d7f84177e53)

So then, I checked my match history on the website. The first game uploaded within a minute, the second took several minutes and refreshes to upload, but eventually showed up.

![image](https://github.com/user-attachments/assets/7ce0523a-97a4-4bfd-8ace-c643ad6e0339)

I believe these are the replay files:

[PairOfXulGames.zip](https://github.com/user-attachments/files/18189722/PairOfXulGames.zip)

P.S. If you're coming here because my initial message said there's something weird going on, it looks like I just had to wait (several minutes) before both games appeared on the website.

**Comment by Zemill** [comment]
There is a delay between replay upload and visibility on the site.  

The uploader is simply informing you the replay was uploaded, after upload it goes into another process than actually parses the replay for information.   The parsing can get bundled in with 250 other replays to be parsed concurrently, which could be slower than if there was only 1 replay in the queue.  

All that to say, if you see something not showing up, usually your best bet is wait a few minutes

**Comment by nightblade9** [comment]
I think you read the initial issue email and not the edited one.

The uploader indicates that the first match is a duplicate, when it isn't. It still uploads it, though.

**Comment by Zemill** [comment]
> I think you read the initial issue email and not the edited one.
> 
> 
> 
> The uploader indicates that the first match is a duplicate, when it isn't. It still uploads it, though.

That's likely a misunderstanding of what duplicate means here.  Duplicate just means the game has already been uploaded

**Comment by nightblade9** [comment]
Right. I uploaded a game for the first time, and the uploader said it's a duplicate.

Which it wasn't.

Because I uploaded it for the first time.

Despite saying "duplicate" on the client side, the server (correctly) showed both games.

Because they aren't duplicates.

**Comment by nightblade9** [comment]
Updated my initial issue (yet again) to remove any mention of timing, delays, etc. since it seems to be a distraction. Hopefully the core issue (game marked as dupe but appears on site correctly) is clearer now.

**Comment by Zemill** [comment]
> That's likely a misunderstanding of what duplicate means here. Duplicate just means the game has already been uploaded

There are 9 other people in your matches.  If one of those people uploaded the game before you did, then it would should success on their side and duplicate on your side.
