### ISSUE TITLE
Game can potentially crash with Prematch page feature enabled.

### ISSUE THREAD

**Issue by pjmagee** [Heroes-Profile/HeroesProfile.Uploader#8]
Does not happen a lot. Seems to be a rare issue but I'm certain its something to do with this feature and folder/file permissions locking and crashing the game client.

Reporting here since many others may start to use this uploader over the HotsAPI uploader now that HotsAPI uploader is not currently functioning. 

This also allows other users be aware of potential issues.

**Comment by meadowsjared** [comment]
I've found that the only time it the Game crashed for me with the "Prematch page" enabled, was when joining a brawl.  I'm wondering if the crash is related to the brawl hero selection page.  However I'm unable to test it further due to it being disabled.

**Comment by pjmagee** [comment]
The feature has been disabled for now until there is time to look into it.
